version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: mongo
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # painel
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
